### ISSUE TITLE
Destination directory /opt/keycloak/keycloak-23.0.3/standalone/configuration does not exist

### ISSUE THREAD

**Issue by tinhtruong** [ansible-middleware/keycloak#143]
##### SUMMARY

I've got an error when running the playbook to install Keycloak on AlmaLinux 9.3. Details as following:
```
TASK [middleware_automation.keycloak.keycloak : Deploy standalone keycloak config to /opt/keycloak/keycloak-23.0.3/standalone/configuration/keycloak.xml] ***
fatal: [192.168.1.xxx]: FAILED! => {"changed": false, "checksum": "22acea149f5e2da64f026fb4dcc50f46a1a6976b", "msg": "Destination directory /opt/keycloak/keycloak-23.0.3/standalone/configuration does not exist"}
```

##### ISSUE TYPE
 - Bug Report

##### ANSIBLE VERSION

```
ansible [core 2.16.2]
  config file = /Users/xxx/Code/self-hosted/proxmox/nodes/mac-mini/ansible/ansible.cfg
  configured module search path = ['/Users/xxx/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/xxx/.asdf/installs/ansible/9.1.0/venv/lib/python3.11/site-packages/ansible
  ansible collection location = /Users/xxx/.ansible/collections:/usr/share/ansible/collections
  executable location = /Users/xxx/.asdf/installs/ansible/9.1.0/bin/ansible
  python version = 3.11.5 (main, Sep 28 2023, 17:39:14) [Clang 15.0.0 (clang-1500.0.40.1)] (/Users/xxx/.asdf/installs/ansible/9.1.0/venv/bin/python3)
  jinja version = 3.1.2
  libyaml = True
```

##### COLLECTION VERSION

```
Collection                     Version
------------------------------ -------
community.general              7.4.0  
freeipa.ansible_freeipa        1.12.0 
geerlingguy.mac                2.1.1  
middleware_automation.common   1.1.4  
middleware_automation.keycloak 2.0.1
```

##### STEPS TO REPRODUCE

```yaml
---
- name: Setup ID server (FreeIPA, Keycloak)
  hosts: id_server
  become: true
  roles:
    - role: id_server
      vars:
        # keycloak vars
        keycloak_admin_password: "xxxxxx"
        keycloak_offline_install: true
        keycloak_version: 23.0.3
        keycloak_archive: keycloak-23.0.3.zip

```
My custom role id_server main.yml:
```yaml
- name: Invoke keycloak role from collection middleware_automation.keycloak
  ansible.builtin.include_role:
    name: middleware_automation.keycloak.keycloak

```
And I ran sensible playbook on macOS Sonoma 14.2.1

##### EXPECTED RESULTS

Playbook should finish without errors

##### ACTUAL RESULTS

```
TASK [middleware_automation.keycloak.keycloak : Deploy custom keycloak config to /opt/keycloak/keycloak-23.0.3/standalone/configuration/keycloak.xml from] ***
skipping: [192.168.1.xxx]

TASK [middleware_automation.keycloak.keycloak : Deploy standalone keycloak config to /opt/keycloak/keycloak-23.0.3/standalone/configuration/keycloak.xml] ***
fatal: [192.168.1.xxx]: FAILED! => {"changed": false, "checksum": "22acea149f5e2da64f026fb4dcc50f46a1a6976b", "msg": "Destination directory /opt/keycloak/keycloak-23.0.3/standalone/configuration does not exist"}```
