### ISSUE TITLE
keycloak_quarkus_java_home doesn't change the java_home variable in sysconfig file

### ISSUE THREAD

**Issue by LeonFroelje** [ansible-middleware/keycloak#170]
##### ISSUE TYPE
 - Bug Report

##### ANSIBLE VERSION
```
ansible [core 2.16.3]
```

##### COLLECTION VERSION

```
2.1.0
```

##### STEPS TO REPRODUCE

```yaml
- name: Playbook for Keycloak X Hosts with HTTPS enabled
  hosts: all
  vars:
    keycloak_quarkus_java_home: /path/to/java/home
  roles:
    - middleware_automation.keycloak.keycloak_quarkus
```

##### EXPECTED RESULTS

I expected the sysconfig environment file in the systemd service to contain the specified java home 

##### ACTUAL RESULTS

Specifying the keycloak_quarkus_java_home file doesn't change the path in the systemd service file. When changing the variable name to keycloak_java_home it works.
