### ISSUE TITLE
Unable to set hostname-strict-https=false

### ISSUE THREAD

**Issue by RHatDev** [ansible-middleware/keycloak#193]
##### SUMMARY

I am try to deploy middleware_automation.keycloak.keycloak_quarkus with the following playbook:
```yaml
---
- name: Playbook for Keycloak Hosts
  hosts: all
  vars:
    keycloak_quarkus_proxy_mode: edge
    keycloak_quarkus_http_enabled: true
    keycloak_quarkus_hostname_strict: false
   keycloak_quarkus_hostname_strict_backchannel: false
    
    keycloak_quarkus_admin_pass: "remembertochangeme"
    keycloak_quarkus_configure_firewalld: true
  roles:
    - middleware_automation.keycloak.keycloak_quarkus
```

But when I try to connect using HTTP, its admin page keeps blank with a loading animation. To make it work I have to manually put `hostname-strict-https=false` and restart the keycloak service.

Therefore, I am requesting to add `hostname-strict-https` to the role variables.

##### ISSUE TYPE
 - Add role variable `hostname-strict-https = false | true [default]`

**Comment by InfoSec812** [comment]
@rpelisse I will try to take a look at this tomorrow and see if I can submit a pull request.

**Comment by InfoSec812** [comment]
@rpelisse Would it be better if I were to create a new option for a dict of additional configuration options so that more uncommon configuration options could be used without needing a specific variable for each item? Looking something like:

```yaml
keycloak_additional_options:
   hostname-strict-https: true
   some-other-option: foo
   extremely-uncommon-option: bar
```

And those options would be appended to the end of the generated `keycloak.conf`?
