### ISSUE TITLE
Keycloak v17.0.0 supported?

### ISSUE THREAD

**Issue by aboschke** [ansible-middleware/keycloak#21]
##### SUMMARY
Is KeyCloak v17.0.0 supported?\
It seems the latest version changed its directory structure ( i.e. missing  directory /opt/keycloak/keycloak-17.0.0/standalone )

##### ISSUE TYPE
 - Bug Report

##### ANSIBLE VERSION

```
ansible 2.9.27
  config file = /root/.ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Nov 16 2020, 22:23:17) [GCC 4.8.5 20150623 (Red Hat 4.8.5-44)]
```

##### COLLECTION VERSION

```
community
google
middleware_automation
os_migrate
```

##### STEPS TO REPRODUCE

$ansible-playbook --become -i hosts  playbook.yml 

```yaml
- hosts: keycloak_server
  strategy: free

  collections:
  - middleware_automation.keycloak
  tasks:
    - name: Include keycloak role
      include_role:
        name: keycloak
      vars:
        keycloak_admin_password: "deepDarksecret"
        keycloak_version: 17.0.0
        keycloak_configure_firewalld: true
```

##### EXPECTED RESULTS

Installation of KeyCloak v17.0.0

##### ACTUAL RESULTS

```
Everything runs fine until here:

TASK [middleware_automation.keycloak.keycloak : Deploy keycloak config to /opt/keycloak/keycloak-17.0.0/standalone/configuration/keycloak.xml] ***
fatal: [keycloak.example.edu]: FAILED! => changed=false
  checksum: 0ed45176030cca4dce4b3730505aa40ad08e3ec7
  msg: Destination directory /opt/keycloak/keycloak-17.0.0/standalone/configuration does not exist

PLAY RECAP **************************************************************************************************************************************
keycloak.example.edu     : ok=34   changed=0    unreachable=0    failed=1    skipped=10   rescued=0    ignored=0

```
