### ISSUE TITLE
Setting administrator password is too clumsy

### ISSUE THREAD

**Issue by guidograzioli** [ansible-middleware/keycloak#22]
##### SUMMARY

The `keycloak_admin_password` is declared empty in the keycloak role varfile. Given [variable precedence](https://docs.ansible.com/ansible/latest/user_guide/playbooks_variables.html#understanding-variable-precedence) it becomes only possible to set the value in include_task  parameters or commandline. Find a better solution

##### ISSUE TYPE
 - Bug Report

##### COLLECTION VERSION

```
1.0.0
```

##### STEPS TO REPRODUCE

```yaml
- playbook: [..]
  vars:
    keycloak_admin_password: "changeme"
  roles:
     -  keycloak
```

##### EXPECTED RESULTS

keycloak_admin_password is overriden by playbook vars, or by inventory host|group_vars

##### ACTUAL RESULTS

It is only possible to override with extra_vars, or include_role vars

```

```
