### ISSUE TITLE
keycloak_frontend_url property is currently defaulting for the installed keycloak app to be behind a reverse proxy

### ISSUE THREAD

**Issue by kami619** [ansible-middleware/keycloak#24]
##### SUMMARY
keycloak_frontend_url property is currently defaulting for the installed keycloak app to be behind a reverse proxy. Without setting this property value explicitly in the ansible playbook, only api requests are able to communicate with the app but not the browsers

##### ISSUE TYPE
 - Bug Report

##### ANSIBLE VERSION
ansible --version
```
ansible 2.9.27
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/kakella/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.6/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.6.8 (default, Sep  9 2021, 07:49:02) [GCC 8.5.0 20210514 (Red Hat 8.5.0-3)]

```

##### COLLECTION VERSION
```
1.0.0
```

##### STEPS TO REPRODUCE
execute the following command
`ansible-playbook -become -i ../inventory updated.yml -K`

```
- name: Playbook for Keycloak Hosts
  hosts: keycloak
  collections:
    - middleware_automation.keycloak
  tasks: 
    - name: Include keycloak role
      ansible.builtin.include_role:
        name: middleware_automation.keycloak.keycloak
      vars:
        keycloak_admin_password: "changeme"
```

##### EXPECTED RESULTS
We expect the keycloak application to work without issue when accessed from the browser after running the playbook and verifying the keycloak service is up and running

##### ACTUAL RESULTS
We are getting ERR_CONNECTION_REFUSED from the browser when we access any url's which have redirects.

##### WORK AROUND
Once we add the below var in the vars section of the playbook, it runs without issue.
`keycloak_frontend_url: http://localhost:8080/auth`
