### ISSUE TITLE
Default JDK version doesn't match version specified by Keycloak docs

### ISSUE THREAD

**Issue by liamjones** [ansible-middleware/keycloak#288]
##### SUMMARY

The Keycloak docs state you should use JDK 21: https://www.keycloak.org/getting-started/getting-started-zip
From the look of this commit, this was changed from 17 for KC 25: https://github.com/keycloak/keycloak/commit/262fc09edc510104a1187c526382bc2fa4ff452e
When installing via the keycloak_quarkus role, JDK 17 is installed by default even for versions beyond 25.0.0

##### ISSUE TYPE
 - Bug Report

##### ANSIBLE VERSION

```
ansible [core 2.18.2]
  config file = None
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.13/site-packages/ansible
  ansible collection location = /root/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/local/bin/ansible
  python version = 3.13.3 (main, Apr 22 2025, 00:00:00) [GCC 14.2.1 20250110 (Red Hat 14.2.1-7)] (/usr/bin/python3)
  jinja version = 3.1.5
  libyaml = True
```

##### COLLECTION VERSION

```
Collection                               Version
---------------------------------------- -------
ansible.posix                            2.0.0  
community.docker                         4.5.2  
community.general                        10.7.0 
community.library_inventory_filtering_v1 1.1.1  
community.postgresql                     3.14.2 
containers.podman                        1.16.3 
fedora.linux_system_roles                1.101.1
middleware_automation.common             1.2.2  
middleware_automation.keycloak           3.0.1
```

##### STEPS TO REPRODUCE

Use keycloak_quarkus role with defaults.
Monitor what version of the JDK gets installed

```yaml
---
- name: Playbook for Keycloak X Hosts with HTTPS enabled
  hosts: all
  vars:
    keycloak_quarkus_bootstrap_admin_password: "remembertochangeme"
    keycloak_quarkus_hostname: http://localhost
    keycloak_quarkus_port: 8443
    keycloak_quarkus_log: file
    keycloak_quarkus_proxy_mode: none
  roles:
    - middleware_automation.keycloak.keycloak_quarkus
```

##### EXPECTED RESULTS

The recommended JDK to be installed by default

##### ACTUAL RESULTS

```
TASK [middleware_automation.keycloak.keycloak_quarkus : Install packages: ['openjdk-17-jdk-headless', 'bash', 'unzip', 'procps', 'apt', 'tzdata']] ***
```
