### ISSUE TITLE
Enable features in quarkus

### ISSUE THREAD

**Issue by fxwgr** [ansible-middleware/keycloak#294]
##### SUMMARY

As in #274 it would be very handy if there would be a way to simply enable features, like in the legacy [Keycloak playbook](https://github.com/ansible-middleware/keycloak/blob/3.0.1/roles/keycloak/README.md).

##### ISSUE TYPE
 - Features can't be enabled in current Keycloak Quarkus playbook

**Comment by RanabirChakraborty** [comment]
@fxwgr, so you want to enable the mentioned feature using a variable? just like `keycloak_ha_enabled`? Am I thinking it correctly?

**Comment by fxwgr** [comment]
@RanabirChakraborty for me it would be sufficient to have an variable like in the previously mentioned Keycloak legacy role `keycloak_features: [ { name: 'docker', status: 'enabled' } ]`

**Comment by guidograzioli** [comment]
You can still define enabled/disabled feature using the parameter `keycloak_quarkus_additional_env_vars` (list), like here:

```yaml
    keycloak_quarkus_additional_env_vars:
      - key: KC_FEATURES
        value: clusterless
      - key: KC_FEATURES_DISABLED
        value: persistent-user-sessions,kerberos
```

We could add a parameter for features alone, but it would require a rather complex validation for additional env vars. @hwo-wd wdyt?
