### ISSUE TITLE
Cannot set client secret in role keycloak_realm

### ISSUE THREAD

**Issue by vanduc2514** [ansible-middleware/keycloak#301]
##### SUMMARY

Set secret to `keycloak_clients` does not take any effect. In the role implementation, it does not pass secret to the module `middleware_automation.keycloak.keycloak_client` and keycloak cannot register the client with defined secret

##### ISSUE TYPE
 - Bug Report

##### ANSIBLE VERSION

```
2.18.6
```

##### COLLECTION VERSION
```
3.0.1
```

Example Playbook

```yaml
- role: middleware_automation.keycloak.keycloak_realm
      vars:
        keycloak_realm: "{{ keycloak_ext_realm_master_name }}"
        keycloak_clients:
          - name: OAuth2 Proxy Client
            description: OIDC Client for authenticating with OAuth2 Proxy
            realm: "{{ keycloak_ext_realm_master_name }}"
            client_id: "{{ vault_keycloak_client_oauth2_proxy_id }}"
            secret: "{{ vault_keycloak_client_oauth2_proxy_secret }}" # This does not take any effect
```

##### EXPECTED RESULTS

The role should use secret to register a client

##### ACTUAL RESULTS

The role does use secret, while the module supports it. The client registered in keycloak have generated secret
