### ISSUE TITLE
Module throws error when middleware_automation.redhat_csp_download isn't include, even when its not needed

### ISSUE THREAD

**Issue by anderssh** [ansible-middleware/keycloak#37]
##### SUMMARY

When trying to install RH SSO from a local file archive, i.e. with `keycloak_offline_install = true` the module `middleware_automation.redhat_csp_download.redhat_csp_download` shouldn't be needed. It still throws an error because on line 87 `install.yaml` of the `middleware_automation.keycloak.keycloak` role. This is because it doesn't understand what the `middleware_automation.redhat_csp_download.redhat_csp_download` module is. 

##### ISSUE TYPE
 - Bug Report

##### ANSIBLE VERSION

```
N/A
```

##### COLLECTION VERSION

```
v0.2.5
```

##### STEPS TO REPRODUCE

```yaml
- name: Playbook for Keycloak Hosts
  become: true
  hosts: keykloak_host
  vars:
  - keycloak_offline_install: True
  - keycloak_admin_password: "mypass"
  - keycloak_rhsso_enable: True
  - keycloak_rhsso_download_url: my_local_place/rh-sso-7.5.0-server-dist.zip
  roles:
  - middleware_automation.keycloak.keycloak

```

##### EXPECTED RESULTS

The installation should procede without errors

##### ACTUAL RESULTS

The installer fails because ansible doesn't recognise 
  `middleware_automation.redhat_csp_download.redhat_csp_download`

```
TASK [middleware_automation.keycloak.keycloak : Include install tasks] *********
fatal: [hostname]: FAILED! => {"reason": "couldn't resolve module/action 'middleware_automation.redhat_csp_download.redhat_csp_download'. This often indicates a misspelling, missing collection, or incorrect module path.

The error appears to be in '.../middleware_automation/keycloak/roles/keycloak/tasks/install.yml': line 87, column 3, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

- name: Perform download from RHN
  ^ here
"}
```
