### ISSUE TITLE
Cannot set more than 1 mod_cluster reverse proxy in standalone.*.xml

### ISSUE THREAD

**Issue by ldileonardorh** [ansible-middleware/keycloak#56]
##### SUMMARY
In production Env, with a HA configuration, it would be suggested to have (at least) 2 mod_cluster instances registered in Keycloak / SSO configuration File.
This collection does not allow multiple mod_cluster proxy configuration.

if HA is configured :
```
keycloak_ha_enabled: True
```
attributes of reverse proxy must be specified:
```
keycloak_modcluster_url: "{{ PROXY_IP_ADDRESS }}"
```

##### ISSUE TYPE
 - Bug Report

##### ANSIBLE VERSION

```
ansible [core 2.14.2]
```

##### COLLECTION VERSION

```
middleware_automation.infinispan          1.1.2  
middleware_automation.keycloak            1.1.0  
middleware_automation.redhat_csp_download 1.2.2  
middleware_automation.wildfly             1.3.1
```

##### CURRENT AVAILABLE SETUP

```
- name: Playbook for Wildfly Hosts - Host 1
  hosts: keycloak
  collections:
    - middleware_automation.keycloak
  tasks:
    - name: Include keycloak role
      ansible.builtin.include_role:
        name: middleware_automation.keycloak.keycloak 
      vars:
        keycloak_jvm_package: "java-11-openjdk-headless.x86_64"
        keycloak_ha_enabled: True
        keycloak_config_standalone_xml: "standalone-ha.xml"
        keycloak_admin_user: "admin"
        keycloak_admin_password: "myadminpassword"
        keycloak_db_enabled: True
        keycloak_jdbc_engine: "postgres"
        keycloak_jdbc_url: "jdbc:postgresql://mycustomdbhost:5432/sso?currentSchema=rh_sso" 
        keycloak_jdbc_driver_version: "42.0.0" 
        keycloak_db_user: "sso_user"
        keycloak_db_pass: "myCustomPassword_1234"
        keycloak_management_port_bind_address: "0.0.0.0"
        keycloak_host: "node1.mysso.redhat.rh"
        keycloak_modcluster_frontend_url: "http://mycustommodclusterfrontend/auth"
        keycloak_modcluster_url: "mycustommodclusterurl"
        keycloak_modcluster_enabled: "True"
        keycloak_infinispan_url: "myInfinispancustomurl"
        keycloak_infinispan_user: "supervisor"
        keycloak_infinispan_pass: "supervisorpassword"
```

##### EXPECTED RESULTS

```
<outbound-socket-binding name="mod_cluster_balancer">
              <remote-destination host="mod_cluster_host_1" port="6666"/>
</outbound-socket-binding>
<outbound-socket-binding name="mod_cluster_balancer_2">
              <remote-destination host="mod_cluster_host_2" port="6666"/>
</outbound-socket-binding>
```

##### ACTUAL RESULTS

```
{% if keycloak_modcluster.enabled %}        
        <outbound-socket-binding name="proxy1">
            <remote-destination host="{{ keycloak_modcluster.reverse_proxy_url | default('localhost') }}" port="6666"/>
        </outbound-socket-binding>
{% endif %}  
```
