### ISSUE TITLE
Setup properties in the `hostname` spi from the vars

### ISSUE THREAD

**Issue by rmarting** [ansible-middleware/keycloak#83]
##### SUMMARY

The current `hostname` spi is fixed by the `standalone(-ha).xml.j2` templates without the capability to define different values, or to add extra properties. In some cases, it is needed to add some additional properties to set up this component in a good way for the ecosystem where Keycloak is running. 

The current definition of this spi is similar to:

```xml
            <spi name="hostname">
                <default-provider>default</default-provider>
                <provider name="default" enabled="true">
                    <properties>
                        <property name="frontendUrl" value="{{ keycloak_modcluster.frontend_url }}"/>
                        <property name="forceBackendUrlToFrontendUrl" value="true"/>
                    </properties>
                </provider>
            </spi>
```

This template does not allow to change the `forceBackendurlToFrontendUrl` property or to add others like `adminUrl`.

This feature request wants to allow to extend the capabilities of this spi to define a list of properties to apply as part of the configuration of the playbook.

###### Implementation Approach

For example a way of implementation could be defining a set of new properties to enable these properties, for example with something similar to:

```yaml
- name: Playbook for Red Hat SSO Hosts
  hosts: sso
  vars_files:
    - ../vars/variables.yml
  collections:
    - redhat.sso
  tasks:
    - name: Include SSO role
      ansible.builtin.include_role:
        name: redhat.sso.sso
      vars:
        sso_offline_install: True
        sso_apply_patches: "{{ rh_sso_apply_patches }}"
        eap_properties:
          - name: property1-name
            value: property1-value
          - name: property2-name
            value: property2-value
        spi:
          hostname:
            properties:
              forceBackendUrlToFrontendUrl: false
              adminUrl: adminUrl-value
```             

The `spi.hostname.properties` is a list of key-value properties to add in this spi automatically as part of the automation process.

The implementation could be done updating the `standalone.xml.j2`, `standalone-ha.xml.j2` templates, or include a loop to add each attribute using the cli tool

The following tasks using the CLI could be an example of implementation:

```yaml
  #
  tasks:
    - name: 'Setting hostname spi properties'
      ansible.builtin.command: >
        {{ keycloak.cli_path }} --connect --command='/subsystem=keycloak-server/spi=hostname/provider=default:write-attribute(name=properties.{{ item.name }},value={{ item.value}})'
      loop: "{{ spi.hostname.properties | dict2items }}"
      changed_when: false
      register: cli_result
```

**NOTE**: Sorry, I am not an Ansible expert, sorry for any typo in the Ansible syntax.

##### ISSUE TYPE
 - Feature Idea
