### ISSUE TITLE
Wait until keycloak becomes active http://localhost:9990/health

### ISSUE THREAD

**Issue by ayoubch11** [ansible-middleware/keycloak#96]
##### SUMMARY
i tried install keycklock with ha_mod but always i have a problem in this step : Wait until keycloak becomes active http://localhost:9990/health

##### STEPS TO REPRODUCE
```yaml
- name: Playbook for Wildfly Hosts - Host 1
  hosts: keycloak
  collections:
    - middleware_automation.keycloak
  tasks:
    - name: Include keycloak role
      ansible.builtin.include_role:
        name: middleware_automation.keycloak.keycloak 
      vars:
        keycloak_ha_enabled: True
        keycloak_admin_user: "admin"
        keycloak_host: "kube1"
        keycloak_modcluster_url: 192.168.56.200
        keycloak_modcluster_enabled: "True"
```

##### ACTUAL RESULTS

```
[curl  -I http://localhost:9990/health
HTTP/1.1 503 Service Unavailable
Connection: keep-alive
Content-Type: application/json
Content-Length: 114364

Date: Mon, 19 Jun 2023 15:06:46 GMT](fatal: [192.168.56.72]: FAILED! => {"attempts": 25, "changed": false, "connection": "close", "content_length": "114364", "content_type": "application/json", "date": "Mon, 19 Jun 2023 15:05:15 GMT", "elapsed": 0, "msg": "Status code was 503 and not [200]: HTTP Error 503: Service Unavailable", "redirected": false, "status": 503, "url": "http://localhost:9990/health"})

```
